// <auto-generated />
using System;
using CarSharing_Angajati.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarSharing_Angajati.Migrations
{
    [DbContext(typeof(CarSharingDbContext))]
    [Migration("20230116110653_Initial Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarSharing_Angajati.Models.Employees", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"), 1L, 1);

                    b.Property<string>("EmpAdress")
                        .IsRequired()
                        .HasColumnType("Nvarchar(150)");

                    b.Property<DateTime>("EmpBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmpDriverLicense")
                        .IsRequired()
                        .HasColumnType("Nvarchar(50)");

                    b.Property<int>("EmpIDNP")
                        .HasColumnType("int");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("Nvarchar(50)");

                    b.Property<string>("EmpPhoneNumber")
                        .IsRequired()
                        .HasColumnType("Nvarchar(18)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.HasKey("EmpId");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
